### ISSUE TITLE
Dead OutPoint encountered when sending transaction

### ISSUE THREAD

**Issue by lostpg** [ququzone/ckb-sdk-go#20]
I am deploying a contract on the dev chain using the go sdk, with Go code [here](https://gist.github.com/lostpg/ee1b2f50a4276840198150e3372e2728#file-deploy-contract-go).

But when I was trying to raise a transaction, it failed with a log

```
2020/05/13 17:52:03 send transaction error: OutPoint: Dead(OutPoint(0x120803ff0f9891c2278f26d605f4e67e1b462a1a3ebbf0444ed17e74198920f000000000))
exit status 1
```
Maybe I made this error by [using](https://gist.github.com/lostpg/ee1b2f50a4276840198150e3372e2728#file-collect-inputs-go) `CellCollector` wrongly. How can I get all live cells correctly?

**Comment by lostpg** [comment]
It seems that this problem is caused by code [here](https://github.com/ququzone/ckb-sdk-go/blob/438a73bc3ad0973a25ba043b9970b9f87120b7e6/utils/cell_collector.go#L109).

The JSON rpc [`get_cells_by_lock_hash`](https://docs.ckb.dev/docs/docs/HTTPRPC/rpc-specification#get_cells_by_lock_hash) returns live cells in block range [from, to], which means the cells in the block at height `to` are counted in. 

While the code below will count in some cells twice as the `for` loop goes.

```go
func (c *CellCollector) collectFromBlocks(lockHash types.Hash) (*CollectResult, error) {
        // omitted snippets 
	for {
		end := start + 100
                // omitted snippets 
		start += 100
	}
	return &result, nil
}
```

As for the solution, a slight change may work.

```go
start += 100 // -> start += 101
```

**Comment by ququzone** [comment]
@lostpg thanks, v0.2.2 already fixed this bug.
